# config/services.yaml
parameters: { }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # === ALIASY INTERFEJSÓW ===
    App\Service\UserServiceInterface: '@App\Service\UserService'
    App\Service\TagServiceInterface: '@App\Service\TagService'
    App\Service\CategoryServiceInterface: '@App\Service\CategoryService'
    App\Service\RecipeServiceInterface: '@App\Service\RecipeService'
    App\Service\CommentServiceInterface: '@App\Service\CommentService'
